import { ResumeProfile } from "./types";

export const initialProfiles: ResumeProfile[] = [
  {
    id: "fs-eng",
    label: "Alex Rivera (Software Engineer)",
    candidateName: "Alex Rivera",
    jobTitle: "Senior AI Full-Stack Engineer",
    atsScore: 78,
    pdfFileName: "alex_rivera_resume_2026.pdf",
    missingSkills: ["PyTorch", "Kubernetes", "Next.js 15 Server Actions", "gRPC APIs", "Distributed Systems Cache"],
    targetCompanies: [
      {
        id: "tc-1",
        name: "Netflix",
        role: "Senior Full-Stack Engineer - AI Personalization",
        matchScore: 92,
        reason: "Highly compatible with Netflix's real-time personalization platform and engineering-freedom culture. Strong React & Node background aligns with core client platforms.",
        location: "Los Gatos, CA (Hybrid)",
        salary: "$280k - $360k + Stock"
      },
      {
        id: "tc-2",
        name: "OpenAI",
        role: "AI Orchestration Platform Engineer",
        matchScore: 88,
        reason: "Fits the multi-agent scaling team perfectly, which requires robust TypeScript, high-concurrency Node.js, and Python backend orchestrations.",
        location: "San Francisco, CA (In-Office)",
        salary: "$250k - $320k + Equity"
      },
      {
        id: "tc-3",
        name: "Stripe",
        role: "Staff Engineer - AI Billing Core",
        matchScore: 85,
        reason: "Excellent alignment with AI Billing Core systems requiring high-reliability API architectures, ledger synchronization, and scalable web frameworks.",
        location: "Seattle, WA (Hybrid)",
        salary: "$220k - $290k + Equity"
      }
    ],
    interviewQuestions: [
      {
        id: "q-1",
        companyName: "Netflix",
        question: "How would you design a highly scalable, low-latency API to deliver dynamic thumbnail variations generated by AI agents to 200M+ concurrent users?",
        category: "System Design",
        difficulty: "Hard",
        tips: "Focus on edge caching (CDNs), pre-computing popular assets, standardizing format dimensions, and using a resilient cache tier like Redis or Memcached with fallback strategies.",
        sampleAnswer: "I would approach this by using a multi-tiered architecture: 1) Client requests are hit at regional Edge Servers (AWS CloudFront / Netflix Open Connect) which cache images. 2) If miss, route to an Express API Gateway that checks a distributed cache (Redis cluster). 3) For missing sizes/crops, route to an asynchronous serverless processing pool which uses libvips or similar fast engines, storing the asset in S3 and updating the CDN metadata instantly. Generative AI previews should be pre-rendered asynchronously in bulk or during low-traffic periods to protect user-facing latency."
      },
      {
        id: "q-2",
        companyName: "Netflix",
        question: "Explain how you would implement resilient streaming for real-time agent output (SSE/WebSockets) when a user's network connection is unstable.",
        category: "Technical Frontend",
        difficulty: "Medium",
        tips: "Talk about exponential backoff reconnection, tracking message offset IDs to resume streams without duplication, and client-side buffer states.",
        sampleAnswer: "For real-time agent streams (like chat or code generation), I prefer Server-Sent Events (SSE) over WebSockets because SSE has native browser reconnection out of the box. To handle severe instability, every token chunk sent from the backend must include a sequence index. The client caches incoming tokens. If connection drops, the client triggers an exponential backoff retry sending the 'Last-Event-ID' (highest index received). The server then resumes broadcasting from that index instead of restarting from scratch."
      },
      {
        id: "q-3",
        companyName: "OpenAI",
        question: "What are the engineering trade-offs of processing agent workloads client-side vs. server-side when designing high-concurrency applications?",
        category: "Architecture",
        difficulty: "Medium",
        tips: "Consider bundle size, device capabilities, latency, data privacy, and secret key protection.",
        sampleAnswer: "Client-side processing (e.g. running Transformers.js or web-assembly) offers zero server billing costs and 100% data privacy since secrets and data never leave the client's device. However, it strains battery life, increases initial bundle size significantly, and risks exposing proprietary models. Server-side processing keeps credentials secure and allows high-performance computing (GPUs/orchestrated clusters), but introduces scaling bottlenecks, network round-trips, and substantial cloud hosting overhead."
      },
      {
        id: "q-4",
        companyName: "OpenAI",
        question: "How would you optimize database lookups for high-throughput prompt tracing in a system that executes millions of multi-agent nested steps daily?",
        category: "Backend Databases",
        difficulty: "Hard",
        tips: "Discuss indexing strategies, read replicas, time-series partitioning, and asynchronous telemetry logging.",
        sampleAnswer: "Because prompt traces are read-heavy but written constantly, we should: 1) Decouple telemetry from the main transactional DB using a message queue (Kafka/RabbitMQ) that batches writes. 2) Store raw trace trees in a document store or partitioned NoSQL DB (like Bigtable or TimescaleDB) indexed by trace_id and timestamp. 3) Leverage a write-behind cache mechanism so that active runs are kept in Redis and only flushed to cold storage once the agent workflow terminates or reaches an idle state."
      },
      {
        id: "q-5",
        companyName: "Stripe",
        question: "How do you guarantee transaction idempotency in an AI agent-driven checkout system where agents might repeat failed billing requests due to model timeout?",
        category: "APIs & Security",
        difficulty: "Hard",
        tips: "Explain idempotency keys, unique request hashes, lock periods, and double-spend protection.",
        sampleAnswer: "To prevent double billing: 1) Require the AI Agent to generate and send a unique client-side UUID as an 'Idempotency-Key' HTTP header. 2) When received, check a Redis distributed lock for that key. If key exists and is in progress, return a 409 Conflict. 3) If key exists and has completed, return the cached response instantly. 4) Use database-level unique constraints (e.g., unique index on the idempotency key and user ID) to secure absolute atomic execution."
      }
    ],
    sevenDayPlan: [
      {
        day: "Day 1",
        title: "PyTorch & Tensor Operations Mastery",
        tasks: [
          "Study tensor manipulations, shape transformations, and PyTorch autograd pipelines.",
          "Write a simple MLP from scratch using PyTorch to understand backward pass mechanics.",
          "Examine model quantization techniques (FP16 vs INT8) to optimize on-device execution."
        ],
        focusArea: "Deep Learning Fundamentals"
      },
      {
        day: "Day 2",
        title: "Kubernetes Deployment & Scaling",
        tasks: [
          "Design a multi-container pod structure to isolate frontend, fast API, and GPU-based model inference.",
          "Configure K8s horizontal pod autoscalers based on GPU-utilization custom metrics.",
          "Establish high-reliability liveness/readiness probes that handle sluggish agent cold starts gracefully."
        ],
        focusArea: "Infrastructure & Orchestration"
      },
      {
        day: "Day 3",
        title: "React Server Components & Next.js 15 Streaming",
        tasks: [
          "Build a custom responsive UI utilizing Next.js Suspense boundaries to render asynchronous stream widgets.",
          "Review Server Actions payload limits and secure environment variable isolation practices.",
          "Optimize Lighthouse performance scores by eliminating layout shifts during progressive streaming."
        ],
        focusArea: "Frontend Performance"
      },
      {
        day: "Day 4",
        title: "gRPC Protocols & Schema Definitions",
        tasks: [
          "Define clean Protobuf syntax schemas for structured AI agent coordination commands.",
          "Implement a high-throughput multiplexed gRPC client-server link using TypeScript.",
          "Profile memory footprint difference between JSON payloads and binary Protobuf arrays."
        ],
        focusArea: "High-Performance Communication"
      },
      {
        day: "Day 5",
        title: "Netflix System Design Drill",
        tasks: [
          "Draft an end-to-end system design for Netflix personalized homepage artwork distribution.",
          "Calculate peak bandwidth requirements and cache eviction rates for 250M daily active viewers.",
          "Practice failover procedures for degraded network states during video stream handshakes."
        ],
        focusArea: "System Architecture & Scalability"
      },
      {
        day: "Day 6",
        title: "Agent Prompt Cache Optimization",
        tasks: [
          "Evaluate financial cost benefits of implementing prompt cache boundaries in Anthropic/OpenAI.",
          "Write a middleware to compute semantic hash similarities on user inputs to hit warm caches.",
          "Tune temperature and top-p parameters to minimize variability in structured JSON format responses."
        ],
        focusArea: "Cost Engineering & LLM Performance"
      },
      {
        day: "Day 7",
        title: "Portfolio Refinement & Deployment",
        tasks: [
          "Host an open-source model proxy server on Cloud Run using serverless configurations.",
          "Polish your personal GitHub repositories, emphasizing structured system architecture readmes.",
          "Conduct a mock technical interview focusing on latency, concurrency, and security trade-offs."
        ],
        focusArea: "Final Prep & Launch"
      }
    ]
  },
  {
    id: "data-science",
    label: "Sarah Chen (Data Scientist)",
    candidateName: "Sarah Chen",
    jobTitle: "Lead Data Scientist (Generative AI)",
    atsScore: 84,
    pdfFileName: "sarah_chen_generative_ai_resume.pdf",
    missingSkills: ["LLMOps", "Vector Databases (Milvus/Qdrant)", "RAG Evaluation (Ragas)", "LangSmith", "CUDA Programming"],
    targetCompanies: [
      {
        id: "tc-4",
        name: "Google",
        role: "Lead Research Scientist - Gemini Foundations",
        matchScore: 94,
        reason: "Ideal fit for Gemini Foundations team. Deep research into reinforcement learning, fine-tuning, and scalable tokenizations aligns directly with Google's Core ML goals.",
        location: "Mountain View, CA (Hybrid)",
        salary: "$300k - $380k + Stock Options"
      },
      {
        id: "tc-5",
        name: "Anthropic",
        role: "Technical Lead - Helpful & Harmless Alignment",
        matchScore: 91,
        reason: "Excellent match for Anthropic's alignment and RLHF engineering team. Proven history in constitutional AI and semantic guardrails fits perfectly.",
        location: "San Francisco, CA (In-Office)",
        salary: "$260k - $340k + Equity"
      },
      {
        id: "tc-6",
        name: "Meta",
        role: "Principal AI Researcher - LLaMA Core Team",
        matchScore: 87,
        reason: "Strong compatibility with LLaMA open-source implementation, model optimization pipelines, and distributed pipeline parallelisms across GPU server grids.",
        location: "Menlo Park, CA (Hybrid)",
        salary: "$270k - $350k + Equity"
      }
    ],
    interviewQuestions: [
      {
        id: "q-6",
        companyName: "Google",
        question: "How does the self-attention mechanism scale with context window length, and how do RingAttention or FlashAttention solve the quadratic complexity bottleneck?",
        category: "ML Theory",
        difficulty: "Hard",
        tips: "Review SRAM vs HBM GPU memory reads, tiling strategies, and block-wise softmax calculations.",
        sampleAnswer: "Standard attention has O(N²) space/time complexity because of the N x N attention matrix. FlashAttention optimizes this by computing softmax block-by-block without storing the full intermediate matrix to HBM (High Bandwidth Memory), utilizing SRAM tiling instead, which cuts down memory I/O and speeds up execution by 2-4x. RingAttention further scales context across multiple GPUs by forming a ring structure where key-value blocks are passed sequentially around the ring, allowing context sizes of millions of tokens."
      },
      {
        id: "q-7",
        companyName: "Anthropic",
        question: "How would you systematically design an automated evaluation pipeline to test an agent's compliance with safety instructions under adversarial jailbreak attempts?",
        category: "AI Safety",
        difficulty: "Hard",
        tips: "Discuss Red Teaming, using LLM-as-a-judge, generating adversarial dataset permutations, and robust metric scoring.",
        sampleAnswer: "I would construct a pipeline consisting of: 1) A curated test bank of adversarial prompts (roleplay, base64 encoding, obfuscation). 2) A prompt runner executing those queries against our active candidate agent. 3) A specialized 'Judge LLM' (with strict system safety guidelines) that reviews the agent responses on a 1-5 scale of compliance. 4) A CI/CD gate that fails deployment if safe compliance rate drops below 99.8% on standard benchmarks or if high-severity jailbreaks succeed."
      },
      {
        id: "q-8",
        companyName: "Meta",
        question: "How do you handle dataset imbalance when fine-tuning an LLM for highly specialized medical classification tasks with limited labeled samples?",
        category: "ML Engineering",
        difficulty: "Medium",
        tips: "Talk about synthetic data generation (using teacher models), prompt templates with few-shot examples, oversampling minority classes, and customized loss weightings.",
        sampleAnswer: "To handle specialized data imbalance: 1) Generate high-quality synthetic negative/positive samples using a larger teacher model (e.g., LLaMA-70B), validating them through expert reviews. 2) Employ weighted cross-entropy loss during SFT to punish misclassification of rare cases more severely. 3) Utilize few-shot prompting techniques with balanced context examples to anchor model reasoning boundaries."
      }
    ],
    sevenDayPlan: [
      {
        day: "Day 1",
        title: "LLMOps & Monitoring Setups",
        tasks: [
          "Deploy a localized instance of LangSmith to trace complex agentic logic execution steps.",
          "Implement system health metrics checking for response hallucination and semantic drifts.",
          "Build an automated alert system triggering when token utilization spikes anomalously."
        ],
        focusArea: "MLOps & Telemetry"
      },
      {
        day: "Day 2",
        title: "Vector Databases & High-Recall Indexing",
        tasks: [
          "Spin up a local Milvus instance and populate it with 100k test document embeddings.",
          "Compare recall precision and querying latencies between IVF-FLAT, HNSW, and Flat indexes.",
          "Implement dynamic metadata filtering to restrict search domains on multi-tenant environments."
        ],
        focusArea: "Information Retrieval"
      },
      {
        day: "Day 3",
        title: "RAG Evaluation Frameworks",
        tasks: [
          "Integrate the Ragas framework to evaluate context relevance, faithfulness, and answer correctness.",
          "Identify and isolate bottlenecking documents that corrupt user query context injections.",
          "Tune chunk sizes (256 vs 512 tokens) with varying overlaps to optimize retrieval metrics."
        ],
        focusArea: "Retrieval-Augmented Generation"
      },
      {
        day: "Day 4",
        title: "CUDA Memory & Matrix Kernels",
        tasks: [
          "Write a clean CUDA kernel to perform high-speed matrix multiplications across GPU threads.",
          "Trace GPU memory bottlenecks using PyTorch Profiler to eliminate red-zone OOM situations.",
          "Study tensor-core optimization techniques and block-wise caching configurations."
        ],
        focusArea: "Hardware-Level Optimization"
      },
      {
        day: "Day 5",
        title: "Google AI Research Whiteboard Drill",
        tasks: [
          "Practice mathematical derivations of attention weights and backprop matrix derivatives.",
          "Detail the pipeline parallelisms used to train large-scale model architectures (Megatron-LM).",
          "Analyze the structural benefits of Mixture of Experts (MoE) over dense transformer structures."
        ],
        focusArea: "Core AI Research"
      },
      {
        day: "Day 6",
        title: "Fine-Tuning Hyperparameter Tuning",
        tasks: [
          "Configure a LoRA fine-tuning run setting varying ranks (8, 16, 32, 64) and alphas.",
          "Measure the degradation rate of base factual knowledge when training on custom niche domains.",
          "Implement a checkpointing strategy saving model weights based on cross-validation loss."
        ],
        focusArea: "Model Fine-Tuning"
      },
      {
        day: "Day 7",
        title: "Anthropic Red Teaming Challenge",
        tasks: [
          "Conduct simulated red-teaming exercises attempting to elicit toxic or restricted data outputs.",
          "Build constitutional AI prompt layers defining absolute behavioral constraints.",
          "Formulate final research summaries describing empirical findings on model alignment levels."
        ],
        focusArea: "AI Alignment & Safety"
      }
    ]
  },
  {
    id: "product-manager",
    label: "Marcus Vance (Product Manager)",
    candidateName: "Marcus Vance",
    jobTitle: "Senior AI Product Manager",
    atsScore: 73,
    pdfFileName: "marcus_vance_pm_resume_v3.pdf",
    missingSkills: ["SQL Analytical Joins", "A/B Testing Power Analysis", "LLM Cost Modeling", "API Product Spec Writing", "Figma Prototyping"],
    targetCompanies: [
      {
        id: "tc-7",
        name: "Apple",
        role: "Senior Product Manager - Apple Intelligence Platform",
        matchScore: 89,
        reason: "Excellent fit for on-device AI product team. Prior experience in local workflow integrations and high-privacy hardware products aligns with Apple's ecosystem.",
        location: "Cupertino, CA (In-Office)",
        salary: "$210k - $275k + RSU Awards"
      },
      {
        id: "tc-8",
        name: "Amazon",
        role: "Principal AI PM - AWS Bedrock Ecosystem",
        matchScore: 86,
        reason: "Amazon's enterprise focus matches your extensive experience in SaaS and B2B products. Excellent fit for scaling serverless prompt templates to cloud clients.",
        location: "Arlington, VA (Hybrid)",
        salary: "$190k - $260k + Sign-On Bonus"
      },
      {
        id: "tc-9",
        name: "Microsoft",
        role: "Senior PM - Azure AI Studio Collaborative Hub",
        matchScore: 85,
        reason: "Great alignment with Azure's developer tools branch. Your background in developer portals and collaborative workspaces is highly valuable here.",
        location: "Redmond, WA (Hybrid)",
        salary: "$200k - $265k + Stock options"
      }
    ],
    interviewQuestions: [
      {
        id: "q-9",
        companyName: "Apple",
        question: "How would you prioritize which feature upgrades should run locally on-device versus utilizing Private Cloud Compute for Apple Intelligence?",
        category: "Product Design",
        difficulty: "Hard",
        tips: "Balance parameters like latency, privacy, model complexity, offline capability, and thermal/battery constraints.",
        sampleAnswer: "I would establish a prioritized framework: 1) Security/Privacy: Highly sensitive data (personal health, local messages) must remain on-device. 2) Latency: Real-time UI controls (keyboard autocomplete, quick Siri actions) must run on-device. 3) Model Complexity: Large, open-domain generative tasks (e.g. detailed document drafting, complex image creation) are routed to Private Cloud Compute with strict cryptographic verification to ensure zero data persistence. 4) Battery/Thermal bounds: Offload processing when device runs hot or low on battery."
      },
      {
        id: "q-10",
        companyName: "Amazon",
        question: "AWS Bedrock needs to reduce customer onboarding friction by 40%. What product enhancements do you propose to streamline early prompt testing?",
        category: "Product Execution",
        difficulty: "Medium",
        tips: "Think about playgrounds, template libraries, out-of-the-box system comparisons, and cost calculators.",
        sampleAnswer: "I propose three high-impact features: 1) One-Click Playground comparison: Allow users to paste a prompt and test it across Anthropic, Meta, and Cohere models side-by-side with automatic latency, cost, and output benchmarks. 2) Pre-built Industry Blueprint Templates (e.g., e-commerce routing, healthcare chat) to copy instantly. 3) Auto-Quantization Optimizer: A system recommending the cheapest model configuration that meets the customer's response quality criteria."
      }
    ],
    sevenDayPlan: [
      {
        day: "Day 1",
        title: "SQL Analytical Mastery",
        tasks: [
          "Complete advanced interactive SQL exercises practicing window functions (PARTITION BY, ROW_NUMBER).",
          "Draft complex dashboard cohort analysis queries tracking weekly user session decay rates.",
          "Optimize database indexes for fast query execution on user engagement tables."
        ],
        focusArea: "Data & Metrics"
      },
      {
        day: "Day 2",
        title: "A/B Testing Foundations",
        tasks: [
          "Master statistical power formulas to calculate the sample size needed to detect 2% conversion lifts.",
          "Analyze the trade-offs of using traditional hypothesis testing versus multi-armed bandit strategies.",
          "Define strict metrics guards to prevent sample ratio mismatch (SRM) from spoiling experiments."
        ],
        focusArea: "Product Experimentation"
      },
      {
        day: "Day 3",
        title: "LLM Unit Economics & Caches",
        tasks: [
          "Build a dynamic spreadsheet model calculating unit margins under variable token request volumes.",
          "Estimate savings rate achieved through implementing warm prompt caches in enterprise pipelines.",
          "Write an pricing tier proposal comparing pay-as-you-go billing against flat user seat subscriptions."
        ],
        focusArea: "Financial Modeling"
      },
      {
        day: "Day 4",
        title: "API Specifications & Specs",
        tasks: [
          "Draft a complete OpenAPI YAML specification defining a high-throughput AI transcription gateway.",
          "Write a high-fidelity Product Requirement Document (PRD) detailing error handling guidelines.",
          "Review developer API documentation examples focusing on clear sample request-response payloads."
        ],
        focusArea: "Technical Specifications"
      },
      {
        day: "Day 5",
        title: "Interactive Figma Layouts",
        tasks: [
          "Design high-fidelity interactive screens showcasing a multi-model comparison workspace.",
          "Validate responsive layouts across standard mobile dimensions and ultrawide monitor formats.",
          "Conduct a mock design feedback session, incorporating comments into revised vector layouts."
        ],
        focusArea: "UI/UX & Prototyping"
      },
      {
        day: "Day 6",
        title: "Amazon PM Mock PR/FAQ Review",
        tasks: [
          "Draft a mock Amazon-style Press Release (PR/FAQ) for an autonomous code-refactoring service.",
          "Defend feature prioritization and pricing assumptions before simulated business stakeholders.",
          "Iterate on FAQ answers addressing potential privacy, latency, and compliance challenges."
        ],
        focusArea: "Product Strategy & Communication"
      },
      {
        day: "Day 7",
        title: "Behavioral Scenarios Drill",
        tasks: [
          "Prepare 5 detailed case histories highlighting cross-functional leadership and crisis management.",
          "Format experiences utilizing the STAR model (Situation, Task, Action, Result) with core metrics.",
          "Record mock video sessions, critiquing pacing, enthusiasm, and structural clarity."
        ],
        focusArea: "Final Polish & Interview Practice"
      }
    ]
  }
];
